# Generated by Django 4.2.11 on 2025-04-16 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='patient_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of the medical visit')),
                ('diagnosis_category', models.CharField(choices=[('GEN', 'General Checkup'), ('CHR', 'Chronic Condition'), ('ACS', 'Acute Syndrome'), ('INJ', 'Injury'), ('PRV', 'Preventive Care'), ('OTH', 'Other')], help_text='Broad category of the diagnosis', max_length=3)),
                ('diagnosis_details', models.TextField(blank=True, help_text='Detailed description of the diagnosis', null=True)),
                ('treatment', models.TextField(blank=True, help_text='Prescribed treatment or medical intervention', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional medical notes or observations', null=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='Recommended date for follow-up appointment', null=True)),
                ('attending_doctor', models.ForeignKey(help_text='Doctor who treated the patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_treated', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient associated with this medical record', on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='medilab.patient')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-visit_date'],
                'indexes': [models.Index(fields=['patient', 'visit_date'], name='medilab_med_patient_a44400_idx'), models.Index(fields=['attending_doctor', 'visit_date'], name='medilab_med_attendi_eab2f7_idx')],
            },
        ),
    ]
