# Generated by Django 4.2.11 on 2025-03-25 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Patient's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Patient's last name", max_length=100)),
                ('birthdate', models.DateField(help_text="Patient's date of birth")),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer Not to Say')], default='N', help_text="Patient's gender", max_length=1)),
                ('address', models.TextField(blank=True, help_text="Patient's full address", null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='medilab_pat_last_na_aed48e_idx')],
            },
        ),
    ]
