# Generated by Django 4.2.11 on 2025-04-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilab', '0004_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id_proof',
        ),
        migrations.AddField(
            model_name='patient',
            name='id_proof_base64',
            field=models.TextField(blank=True, help_text='Base64-encoded image or PDF of ID proof', null=True, verbose_name='ID Proof (Base64)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_proof_content_type',
            field=models.CharField(blank=True, help_text='MIME type of the uploaded file', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_proof_filename',
            field=models.CharField(blank=True, help_text='Original filename of the ID proof', max_length=255, null=True),
        ),
    ]
