# Generated by Django 4.2.11 on 2025-04-09 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medilab', '0006_patientprofileapplication_patientprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofileapplication',
            name='existing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_applications', to='medilab.patientprofile'),
        ),
        migrations.AddField(
            model_name='patientprofileapplication',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
