# Generated by Django 4.2.11 on 2025-03-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0003_alter_visitor_status_alter_visitor_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('admin', 'Admin'), ('officer', 'Officer')], default='resident', max_length=50),
        ),
    ]
