# Generated by Django 4.2.11 on 2025-03-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0004_alter_residence_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='role',
            field=models.CharField(choices=[('Resident', 'Resident'), ('Admin', 'Admin'), ('Officer', 'Officer')], default='Resident', max_length=50),
        ),
    ]
