# Generated by Django 4.2.11 on 2025-05-28 14:01
from django.db import migrations


def create_groups_with_crud_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    group_permissions = {
        "Officer": [
            "add_event",
            "change_event",
            "delete_event",
            "view_event",
        ],
        "Resident": ["view_event"],
        "Guard": ["view_event"],
    }

    for group_name, codenames in group_permissions.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        perms = Permission.objects.filter(codename__in=codenames)
        group.permissions.set(perms)
        group.save()


def remove_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Officer", "Resident", "Guard"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0009_communityresource'),
    ]

    operations = [
        migrations.RunPython(
            create_groups_with_crud_permissions, remove_groups
        ),
    ]
