# Generated by Django 4.2.11 on 2025-05-30 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# --- Function to add initial data ---
def create_initial_document_categories(apps, schema_editor):
    DocumentCategory = apps.get_model("residence", "DocumentCategory")
    # You might need to adjust 'residence' to your actual app name if it's different.

    categories_to_create = [
        "Community Rules",
        "Community Resources",
        "Forms and Requests",
    ]

    for category_name in categories_to_create:
        # get_or_create is good practice for idempotent migrations
        # It creates the object if it doesn't exist, or gets it if it does.
        DocumentCategory.objects.get_or_create(category_name=category_name)


# --- Function to reverse the initial data creation (optional but good practice) ---
def reverse_initial_document_categories(apps, schema_editor):
    DocumentCategory = apps.get_model("residence", "DocumentCategory")

    categories_to_delete = [
        "Community Rules",
        "Community Resources",
        "Forms and Requests",
    ]

    for category_name in categories_to_delete:
        try:
            category = DocumentCategory.objects.get(category_name=category_name)
            category.delete()
        except DocumentCategory.DoesNotExist:
            pass  # Category already deleted, no need to do anything


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residence', '0011_alter_event_options_remove_issue_resident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="residence.documentcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunityDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "id_document",
                    models.FileField(
                        blank=True, null=True, upload_to="community_documents/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_category",
                        to="residence.documentcategory",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_file",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Document",
                "verbose_name_plural": "Community Documents",
                "ordering": ["id"],
            },
        ),
        # --- Add this operation to create initial data ---
        migrations.RunPython(
            create_initial_document_categories,
            reverse_code=reverse_initial_document_categories,
        ),
    ]
