# Generated by Django 4.2.11 on 2025-05-30 14:56

from django.db import migrations


# --- Copy your data function here ---
def create_initial_document_categories(apps, schema_editor):
    DocumentCategory = apps.get_model("residence", "DocumentCategory")
    # You might need to adjust 'residence' to your actual app name if it's different.

    categories_to_create = [
        "Community Rules",
        "Community Resources",
        "Forms and Requests",
        # Add any new categories here if you want to add more
    ]

    for category_name in categories_to_create:
        DocumentCategory.objects.get_or_create(category_name=category_name)


def reverse_initial_document_categories(apps, schema_editor):
    DocumentCategory = apps.get_model("residence", "DocumentCategory")
    categories_to_delete = [
        "Community Rules",
        "Community Resources",
        "Forms and Requests",
        # Add any new categories here if you want to delete them on reverse
    ]
    for category_name in categories_to_delete:
        try:
            category = DocumentCategory.objects.get(category_name=category_name)
            category.delete()
        except DocumentCategory.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        # The dependency should be the last migration before this new one.
        # In your case, it would be your 0012 migration.
        (
            "residence",
            "0012_documentcategory_communitydocument",
        ),  # Replace with actual 0012 name
    ]

    operations = [
        migrations.RunPython(
            create_initial_document_categories,
            reverse_code=reverse_initial_document_categories,
        ),
    ]
