# Generated by Django 4.2.11 on 2025-05-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0013_auto_20250530_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
    ]
