# Generated by Django 4.2.11 on 2025-05-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0018_alter_residence_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('guard', 'Guard'), ('officer', 'Officer')], default='resident', max_length=50),
        ),
    ]
