# Generated by Django 4.2.11 on 2025-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0019_alter_residence_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='role',
            field=models.CharField(choices=[('Resident', 'Resident'), ('Guard', 'Guard'), ('Officer', 'Officer')], default='Resident', max_length=50),
        ),
    ]
