# Generated by Django 4.2.11 on 2025-06-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0023_alter_issue_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['id'], 'verbose_name': 'Community Category', 'verbose_name_plural': 'Community Categories'},
        ),
    ]
