# Generated by Django 4.2.11 on 2025-06-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0024_alter_documentcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
