# Generated by Django 4.2.11 on 2025-06-21 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residence', '0026_residence_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to resolve the issue. Must be an Officer or Guard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
