# Generated by Django 4.2.11 on 2025-06-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0028_alter_event_options_alter_issuecomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance and Infrastructure Issue'), ('security', 'Security and Safety Concern'), ('cleanliness', 'Cleanliness and Sanitation'), ('neighbor', 'Neighbor-Related Complaint'), ('administrative', 'Administrative or Community Concern')], default='maintenance', help_text='Categorize the issue type for better tracking.', max_length=20),
        ),
    ]
