# Generated by Django 4.2.11 on 2025-06-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0029_issue_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Block 1', 'Block 1'), ('Block 2A', 'Block 2A'), ('Block 2A1', 'Block 2A1'), ('Block 2B', 'Block 2B'), ('Block 2C', 'Block 2C'), ('Block 3', 'Block 3'), ('Block 4', 'Block 4'), ('Block 5', 'Block 5'), ('Block 6A', 'Block 6A'), ('Block 6B', 'Block 6B'), ('Block 7', 'Block 7'), ('Block 8', 'Block 8'), ('Block 9', 'Block 9'), ('Block 10', 'Block 10'), ('Block 11', 'Block 11'), ('Block 12', 'Block 12')], default='Block 1', help_text='Select the block where the event will take place.', max_length=20),
        ),
    ]
