# Generated by Django 4.2.11 on 2024-05-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_needs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
