# Generated by Django 4.2.11 on 2024-05-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_event_additional_needs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('application', 'Application'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('draft', 'Draft')], default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='EventEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.equipment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='equipments',
            field=models.ManyToManyField(through='reservation.EventEquipment', to='reservation.equipment'),
        ),
    ]
