# Generated by Django 4.2.11 on 2024-04-29 00:54

from django.db import migrations, models
import django.db.models.deletion
import reservation.models.facility_model


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_facility_remove_employee_employee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='department',
            field=models.ForeignKey(default=reservation.models.facility_model.get_default_department_id, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='reservation.department'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='person_in_charge',
            field=models.ForeignKey(default=reservation.models.facility_model.get_default_person_in_charge, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_facilities', to='reservation.employee'),
        ),
        migrations.DeleteModel(
            name='ReservationRequest',
        ),
    ]
