# Generated by Django 4.2.11 on 2024-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_event_equipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='equipments',
            field=models.ManyToManyField(blank=True, through='reservation.EventEquipment', to='reservation.equipment'),
        ),
    ]
