# Generated by Django 4.2.11 on 2024-04-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.IntegerField(choices=[(1, 'Logistics'), (2, 'MIS'), (3, 'Personnel'), (4, 'Security')], default=1),
        ),
    ]
