# Generated by Django 4.2.11 on 2024-04-29 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_equipment_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Denied'), (5, 'Draft')], default=5)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='reservation.department')),
                ('equipment', models.ManyToManyField(blank=True, related_name='events', to='reservation.equipment')),
                ('organizer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reservation.employee')),
                ('reserved_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reservation.facility')),
            ],
            options={
                'ordering': ['event_name'],
            },
        ),
    ]
