# Generated by Django 4.2.11 on 2024-04-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
