# Generated by Django 4.2.11 on 2024-05-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_event_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='immediate_head_approver',
            field=models.ForeignKey(default='30', on_delete=django.db.models.deletion.CASCADE, related_name='immediate_head_approvals', to='reservation.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approval',
            name='person_in_charge_approver',
            field=models.ForeignKey(default='29', on_delete=django.db.models.deletion.CASCADE, related_name='person_in_charge_approvals', to='reservation.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='equipments',
            field=models.ManyToManyField(blank=True, through='reservation.EventEquipment', to='reservation.equipment'),
        ),
    ]
