# Generated by Django 4.2.11 on 2024-04-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_event_days_of_week_event_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='work_type',
            field=models.IntegerField(choices=[(1, 'Setup only'), (2, 'Dedicated'), (3, 'Overtime')], null=True),
        ),
    ]
