# Generated by Django 4.2.11 on 2024-05-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='slip_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slip_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
