# Generated by Django 4.2.11 on 2024-04-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_equipment_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=7),
        ),
    ]
