# Generated by Django 4.2.11 on 2024-04-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_remove_event_days_of_week_remove_event_is_recurring_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer_name',
            new_name='organizer',
        ),
    ]
