# Generated by Django 4.2.11 on 2024-04-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_rename_organizer_name_event_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applicant_superior_approved', models.BooleanField(default=False)),
                ('facility_authority_approved', models.BooleanField(default=False)),
                ('admin_approved', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='reservation.employee')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='reservation.event')),
            ],
        ),
    ]
