# Generated by Django 4.2.11 on 2024-05-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_event_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
