# Generated by Django 4.2.11 on 2024-05-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_facility_facility_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='admin_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='immediate_head_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='person_in_charge_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='status_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
