# Generated by Django 4.2.11 on 2024-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_facility_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_file',
            field=models.FileField(blank=True, help_text='Upload a PDF or JPEG file.', null=True, upload_to='event_files/'),
        ),
    ]
